services:
  node_bot:
    build: .
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && tail -f /dev/null"]
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - fabiomanzo_network

networks:
  fabiomanzo_network:
    external: true
